### PR TITLE
add monaco theme

### PR DESCRIPTION
**Pull request by hhsnopek**

### CODE REVIEW

**Comment by hhsnopek** [comment]
So I think this is good to go, but I can't seem to link the project to test it out, to add on all these tests are failing ... @kylemac thoughts?

**Comment by hhsnopek** [comment]
Ah okay, so with the way that I've laid out the monaco theme is that it's completely torn apart into it's separate sections, unlike the current jade versions

**Comment by hhsnopek** [comment]
So the tests are failing because `./default.json` from roots-tumblr isn't within `roots-tumblr` after installing the test dependencies

**Comment by hhsnopek** [comment]
@kylemac when you get a moment could you clone down this branch and see if you get the same issue?

**Comment by hhsnopek** [comment]
@kylemac Figured it out `default.json` isn't being published on npm. That's why it's saying it's unable to located `./default`

**Comment by hhsnopek** [comment]
all tests are passing locally here - on travis it keeps timing out waiting for deps to be installed

**Comment by hhsnopek** [comment]
alright now they're failing locally haha

**Comment by hhsnopek** [comment]
Bam! Working! cc @kylemac

**Comment by kylemac** [comment]
1 of 2 :tennis: -- getting closer 

:traffic_light:

**Comment by hhsnopek** [comment]
Not sure if you'll like the fix for it.... see a9019c9

**Comment by kylemac** [comment]
that's fine with me, as long as it fixes it

**Comment by kylemac** [comment]
what is `jstransformer-stylus` all about? is this something more fundamental we need to update in our other roots templates too?

**Comment by hhsnopek** [comment]
it's for jade filters `:stylus`. Jade now uses [jstransformers/jstransformer](https://github.com/jstransformers/jstransformer) for all its' filters and they've deprecated the previous way to use them. So in the next release you must have `jstransform-stylus` for the stylus filter in jade

**Comment by kylemac** [comment]
got it. that's fine. we don't use that filter in our standard templates

**Comment by hhsnopek** [comment]
I actually have a separate package.json located in the monaco folder which contains it and jumblr. I believe sprout should still do it's default changes

**Comment by hhsnopek** [comment]
just reverted 7eebbb2 - all tests should still pass and we should be good to merge

**Comment by kylemac** [comment]
:+1: :tennis:

**Comment by kylemac** [comment]
@hhsnopek have you tried running the sprout-cli with this template manually too?

**Comment by hhsnopek** [comment]
alright - I added the `fs` fix and removed an unused option in `root/app.production`

**Comment by kylemac** [comment]
:+1:

**Comment by hhsnopek** [comment]
:confetti_ball:

**Pull request merged**
